<?php
echo "<html>";
echo "<head>";
echo "<title>Still Into You Lyrics & Chords</title>";
echo "</head>";
echo "<body>";
echo "<div style='text-align: center;'>"; 
echo "<p>";

echo "<h2>Still Into You</h2>";
echo "[Verse 1]<br>";
echo "F<br>";
echo "Can't count the years on one hand<br>";
echo "                       Dm<br>";
echo "That we've been together<br>";
echo "F<br>";
echo "I need the other one to hold you<br>";
echo "                                 Dm<br>";
echo "Make you feel, make you feel better<br>";
echo "F<br>";
echo "It's not a walk in the park<br>";
echo "                Dm<br>";
echo "To love each other<br>";
echo "F<br>";
echo "But when our fingers interlock,<br>";
echo "                                     Dm<br>";
echo "Can't deny, can't deny you're worth it<br><br>";

echo "[Chorus]<br>";
echo "                      Bb<br>";
echo "'Cause after all this time<br>";
echo "    C          F<br>";
echo "I'm still into you<br>";
echo "                         Bb        C<br>";
echo "I should be over all the butterflies<br>";
echo "             F<br>";
echo "But I'm into you (I'm into you)<br>";
echo "                      Bb         C<br>";
echo "And baby, even on our worst nights<br>";
echo "         F<br>";
echo "I'm into you (I'm into you)<br>";
echo "                      Bb       C<br>";
echo "Let 'em wonder how we got this far<br>";
echo "                              Dm         F<br>";
echo "'Cause I don't really need to wonder at all<br>";
echo "                     Bb<br>";
echo "Yeah, after all this time<br>";
echo "    C          F<br>";
echo "I'm still into you<br><br>";

echo "[Verse 2]<br>";
echo "F<br>";
echo "Recount the night that I first<br>";
echo "              Dm<br>";
echo "Met your mother<br>";
echo "F<br>";
echo "And on the drive back to my house<br>";
echo "                                         Dm<br>";
echo "I told you that, I told you that I loved ya<br>";
echo "F<br>";
echo "You felt the weight of the world<br>";
echo "                    Dm<br>";
echo "Fall off your shoulder<br>";
echo "F<br>";
echo "And to your favorite song<br>";
echo "                                  Dm<br>";
echo "We sang along to the start of forever<br><br>";

echo "[Chorus]<br>";
echo "                      Bb<br>";
echo "'Cause after all this time<br>";
echo "    C          F<br>";
echo "I'm still into you<br>";
echo "                         Bb        C<br>";
echo "I should be over all the butterflies<br>";
echo "             F<br>";
echo "But I'm into you (I'm into you)<br>";
echo "                      Bb         C<br>";
echo "And baby, even on our worst nights<br>";
echo "         F<br>";
echo "I'm into you (I'm into you)<br>";
echo "                      Bb       C<br>";
echo "Let 'em wonder how we got this far<br>";
echo "                              Dm         F<br>";
echo "'Cause I don't really need to wonder at all<br>";
echo "                     Bb<br>";
echo "Yeah, after all this time<br>";
echo "    C          F<br>";
echo "I'm still into you<br><br>";

echo "[Solo]<br>";
echo "F    Dm  C  x2<br><br>";

echo "[Verse 3]<br>";
echo "F<br>";
echo "Some things just,<br>";
echo "<br>";
echo "Some things just make sense<br>";
echo "    Dm              C<br>";
echo "And one of those is you and I<br>";
echo "F<br>";
echo "Some things just,<br>";
echo "<br>";
echo "Some things just make sense<br>";
echo "    Dm         C<br>";
echo "And even after all this time<br><br>";

echo "[Bridge]<br>";
echo " Bb   C<br>";
echo "Hey<br>";
echo "         F<br>";
echo "I'm into you<br>";
echo "            Bb<br>";
echo "Baby, not a day goes by that<br>";
echo "    C     F<br>";
echo "I'm not into you<br><br>";

echo "[Final Chorus]<br>";
echo "                         Bb        C<br>";
echo "I should be over all the butterflies<br>";
echo "             F<br>";
echo "But I'm into you (I'm into you)<br>";
echo "                      Bb         C<br>";
echo "And baby, even on our worst nights<br>";
echo "         F<br>";
echo "I'm into you (I'm into you)<br>";
echo "                      Bb       C<br>";
echo "Let 'em wonder how we got this far<br>";
echo "                              Dm         F<br>";
echo "'Cause I don't really need to wonder at all<br><br>";

echo "[Outro]<br>";
echo "                     Bb<br>";
echo "Yeah, after all this time<br>";
echo "    C          Bb<br>";
echo "I'm still into you<br>";
echo "    C          Bb<br>";
echo "I'm still into you<br>";
echo "    C          N.C.<br>";
echo "I'm still into you<br>";

echo "</p>";
echo "</div>";
echo "</body>";
echo "</html>";
?>
